### PR TITLE
Test against rails 4.2 & 5.0

### PR DESCRIPTION
**Pull request by tricknotes**

### CODE REVIEW

**Comment by JacobEvelyn** [comment]
Thanks for doing this! Just trying to get Travis to run the branch before merging (not sure why it didn't run automatically as usual—possibly due to a recent GitHub outage).

**Comment by tricknotes** [comment]
I don't know why Travis CI run test against this PR.
However the branch on my forked repository is passed all test.
https://travis-ci.org/tricknotes/order_as_specified/builds/144458958

**Comment by tricknotes** [comment]
All right!
I updated my commits replacing single-quotes with double-quotes.

**Comment by JacobEvelyn** [comment]
Awesome, thanks! I'm merging this now and I'll release a new version to RubyGems soon. Thanks so much for the contributions!

**Comment by JacobEvelyn** [comment]
This has been released to RubyGems in version 1.1.

**Pull request merged**
